- name: discretizer
  params:
    bins_per_column:
      age: 15
      bmi: 15
    strategy: kmeans
- name: categorical-encoder
  params:
    force_dense_array: true
- name: crosser
  params: {}
- name: standard-scaler
  params: {}
- name: random-forest
  params: {}
