- name: discretizer
  params:
    bins_per_column:
      age: 4
      bmi: 4
    strategy: kmeans
- name: categorical-encoder
  params:
    force_dense_array: true
    one_hot: false
- name: crosser
  params: {}
- name: random-forest
  params: {}
