- name: average-price-extractor
  params: {}
- name: categorical-encoder
  params:
    force_dense_array: true
    one_hot: false
- name: crosser
  params: {}
- name: standard-scaler
  params: {}
- name: linear-regressor
  params: {}
