- name: discretizer
  params:
    bins_per_column:
      age: 2
      bmi: 2
    strategy: kmeans
- name: categorical-encoder
  params:
    force_dense_array: true
    one_hot: true
- name: standard-scaler
  params: {}
- name: gradient
  params: {}
